name: Check for updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  check-for-updates:
    name: "Check for updates"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Version check
        id: "check"
        run: ./check.sh

  update:
    name: "Update AUR package"
    runs-on: ubuntu-latest
    needs: check-for-updates
    if : ${{ needs.check-for-updates.outputs.skip == 'false' }}
    steps:
      - name: Update package
        run: |
          echo "Update failed"
          exit 1
